apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: subkafka
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: kafkatestchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: channel-display0-kafka
